runtime: python
env: flex
entrypoint: gunicorn -b :$PORT LLA.wsgi
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

handlers:

- url: /static
  static_dir: static/

runtime_config:
  python_version: 3

